#!/bin/python

import argparse

parser = argparse.ArgumentParser(description='This will display the commands to run on a device you specify')
parser.add_argument('device', help="Hostname of device") #positional argument
parser.add_argument('interface', help="Interface you need show commands for") #positional argument
parser.add_argument('--detail', '-d', help="show detail intformation of interface", action="store_true") #optional argument '-d', action="store_true will make 
it so that you don't need a value after the option.
args = parser.parse_args()

if args.detail:
    print("ssh %s\nshow int %s detail\nshow int %s-4 trans\nshow lldp neighbors | include %s" % (args.device, args.interface, args.interface, args.interface))
else:
    print("ssh %s\nshow int %s\nshow int %s-4 trans\nshow lldp neighbors | include %s" % (args.device, args.interface, args.interface, args.interface))
